package stream

import (
	"fmt"

	"github.com/Khan/genqlient/graphql"
	"github.com/wandb/wandb/core/internal/featurechecker"
	"github.com/wandb/wandb/core/internal/observability"
	"github.com/wandb/wandb/core/internal/runupserter"
	"github.com/wandb/wandb/core/internal/runwork"
	"github.com/wandb/wandb/core/internal/settings"
	"github.com/wandb/wandb/core/internal/tensorboard"
	"github.com/wandb/wandb/core/internal/wboperation"
	spb "github.com/wandb/wandb/core/pkg/service_go_proto"
)

// RecordIngester turns Records into Work.
//
// Records coming from the client via interprocess communication, or those
// read from a transaction log, pass through here first.
type RecordIngester struct {
	ExtraWork          runwork.ExtraWork
	FeatureProvider    *featurechecker.ServerFeaturesCache
	GraphqlClientOrNil graphql.Client
	Logger             *observability.CoreLogger
	Operations         *wboperation.WandbOperations
	TBHandler          *tensorboard.TBHandler
	Run                *StreamRun

	Settings *settings.Settings
}

// Ingest pushes a record into the run work pipeline.
func (p *RecordIngester) Ingest(record *spb.Record) {
	switch {
	case record.GetRun() != nil:
		p.ExtraWork.AddWork(
			&runupserter.RunUpdateWork{
				Record: record,

				StreamRunUpserter: p.Run,

				Settings:           p.Settings,
				BeforeRunEndCtx:    p.ExtraWork.BeforeEndCtx(),
				Operations:         p.Operations,
				FeatureProvider:    p.FeatureProvider,
				GraphqlClientOrNil: p.GraphqlClientOrNil,
				Logger:             p.Logger,
			})

	// The TensorBoard integration is implemented here, but treated as if it
	// is implemented in the client. See the Exit case.
	case record.GetTbrecord() != nil:
		err := p.TBHandler.Handle(record.GetTbrecord())
		if err != nil {
			p.Logger.CaptureError(
				fmt.Errorf("stream: failed to handle TB record: %v", err))
		}

		// The integration outputs records that are not saved to the transaction
		// log because the information is already contained inside tfevents
		// files. When syncing, we need to know that the TensorBoard integration
		// was activated for the run.
		p.ExtraWork.AddWork(&runwork.SaveRecordWork{Record: record})

	// The client does not send any run-modifying records after Exit.
	//
	// We treat records generated by the TB integration as if the client sent
	// them. If the integration were in the client, the client would stop it and
	// wait for it to finish before sending the Exit record. We simulate that
	// here.
	case record.GetExit() != nil:
		go func() {
			p.TBHandler.Finish()
			p.ExtraWork.AddWork(runwork.WorkFromRecord(record))
		}()

	// Legacy style for handling records where the code to process them
	// lives in handler.go and sender.go directly.
	default:
		p.ExtraWork.AddWork(runwork.WorkFromRecord(record))
	}
}
